apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: astros
  name: astros
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      run: gpu-demo
  template:
    metadata:
      labels:
        run: gpu-demo
    spec:
      containers:
      - image: krudisar/gpu-demo:v2
        imagePullPolicy: Always
        name: gpu-demo
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
