apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: gpu-demo
  name: gpu-demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      run: gpu-demo
  template:
    metadata:
      labels:
        run: gpu-demo
    spec:
      containers:
      - image: krudisar/gpu-demo:v2
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        imagePullPolicy: Always
        name: gpu-demo
      nodeSelector: 
        accelerator: nvidia-tesla-k80
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
